# docker-compose.yml
version: "3.5"

networks:
 fluxit:
  name: fluxit

services:

 server:
   container_name: skills_app
   build: .
   hostname: skills_app
   networks:
     - fluxit
   ports:
     - "5000:5000"
   volumes: [".:/usr/src/app"]
   restart: always
   environment:
     ENV: DEVELOPMENT